name: Run Tests

on: [push, pull_request]

jobs:
  test:
    name: Execute Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        make install

    - name: Run Tests
      run: make test
